List complited
micromirme/ToDoist pull request #8
Opened 2021-04-20 19:48 UTC by TRex-Dino

adios

2021-04-20 19:48 UTC, TRex-Dino commented
change DTO

2021-04-21 05:59 UTC, micromirme requested changes

2021-04-21 05:59 UTC, micromirme commented on ToDoist/DTO/TaskDataManagerImpl.swift
> +    var tasks: [ImportantStatus: [Task]] = [:]
https://ru.wikipedia.org/wiki/Инкапсуляция_(программирование)

2021-04-21 05:59 UTC, micromirme commented on ToDoist/Controllers/ComplitedListViewController.swift
> +        super.viewDidLoad()
зачем оставлять пустые методы если они не используются ?

2021-04-21 05:59 UTC, micromirme commented on ToDoist/Controllers/ComplitedListViewController.swift
> +        return complitedTask.count
ретурн не нужен здесь

2021-04-21 05:59 UTC, micromirme commented on ToDoist/Controllers/ComplitedListViewController.swift
> +
лишний пробел

2021-04-21 05:59 UTC, micromirme commented on ToDoist/Controllers/ComplitedListViewController.swift
> +    var tasks = TaskDataManagerImpl.shared.tasks
раскрывать так нельзя, нарушаешь ООП, расширь протокол если необходимо вытаскивать таски

2021-04-21 17:09 UTC, TRex-Dino commented
fix problem

2021-04-22 07:54 UTC, micromirme approved these changes

2021-04-22 07:54 UTC, merged